eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

server:
  port: 8761